### ISSUE TITLE
Icon coloring problem when setting title to ALWAYS_HIDE

### ISSUE THREAD

**Issue by sedestrian** [aurelhubert/ahbottomnavigation#204] opened 2017-01-16 13:46 UTC
When setting title state to ALWAYS_HIDE, the icons won't color correctly on first tap, they'll color after the second time you tap them.

**Comment by aurelhubert** [comment] 2017-01-16 14:04
Have you tried the demo project? I can't reproduce this problem. Do you use the latest version of the library? Which version of Android do you use?

**Comment by sedestrian** [comment] 2017-01-16 15:10
I haven't tried the demo project but i'm using the latest version (2.0.3) and testing on sdk v25.
This is all the code in my activity

`private AHBottomNavigation mBottomNavigation;
    private AHBottomNavigationViewPager mViewPager;

    //Bottom Navigation Items
    AHBottomNavigationItem mMap;
    AHBottomNavigationItem mTab2;
    AHBottomNavigationItem mTab3;
    AHBottomNavigationItem mMessages;
    AHBottomNavigationItem mUser;

    //General
    private FragmentManager mFragManager;
    private FragmentTransaction mFragTrans;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        mFragManager = getFragmentManager();
        setupViews();
        setupBottomNavigation();
    }

    private void setupViews(){
        mBottomNavigation = (AHBottomNavigation) findViewById(R.id.bottom_navigation);
    }

    private void setupBottomNavigation() {
        mMap = new AHBottomNavigationItem(R.string.tab_1, R.drawable.mapmarker, R.color.colorTabs);
        mTab2 = new AHBottomNavigationItem(R.string.tab_2, R.drawable.bike, R.color.colorTabs);
        mTab3 = new AHBottomNavigationItem(R.string.tab_3, R.drawable.codetags, R.color.colorTabs);
        mMessages = new AHBottomNavigationItem(R.string.tab_4, R.drawable.message, R.color.colorTabs);
        mUser = new AHBottomNavigationItem(R.string.tab_5, R.drawable.face, R.color.colorTabs);

        mBottomNavigation.addItem(mMap);
        mBottomNavigation.addItem(mTab2);
        mBottomNavigation.addItem(mTab3);
        mBottomNavigation.addItem(mMessages);
        mBottomNavigation.addItem(mUser);



        mBottomNavigation.setDefaultBackgroundColor(ContextCompat.getColor(this, R.color.colorTabs));
        mBottomNavigation.setAccentColor(Color.WHITE);
        mBottomNavigation.setInactiveColor(Color.parseColor("#88FFFFFF"));
        mBottomNavigation.setTitleState(AHBottomNavigation.TitleState.ALWAYS_SHOW);
        mBottomNavigation.setOnTabSelectedListener(this);

        mBottomNavigation.setCurrentItem(0);
    }

    @Override
    public boolean onTabSelected(int position, boolean wasSelected) {
        mFragTrans = mFragManager.beginTransaction();
        switch(position){
            case 0:
                mFragTrans.replace(R.id.placeholder, new BottomNavTest1());
                break;
            case 1:
                mFragTrans.replace(R.id.placeholder, new BottomNavTest2());
                break;
            case 2:
                mFragTrans.replace(R.id.placeholder, new BottomNavTest1());
                break;
            case 3:
                mFragTrans.replace(R.id.placeholder, new BottomNavTest2());
                break;
            case 4:
                mFragTrans.replace(R.id.placeholder, new BottomNavTest1());
                break;
        }
        mFragTrans.commit();
        return true;
    }`

If i set the title to ALWAYS_HIDE when i tap an icon the other selected icon stays white while the new selected icon becomes halfway white, when i tap again the old one becomes gray and the new one white

**Comment by aurelhubert** [comment] 2017-01-16 17:21
It should be fixed in the latest version (2.0.4), thanks.

**Closed by aurelhubert** 2017-01-16 17:21 UTC
Labels: bug

**Comment by sedestrian** [comment] 2017-01-16 20:18
Thank you, yes it is fixed.
Awesome library by the way.
