### ISSUE TITLE
UI freezing when using the shared element transitions

### ISSUE THREAD

**Issue by mclhrn** [aurelhubert/ahbottomnavigation#34] opened 2016-04-07 14:10 UTC
Hi, when using the library to start a new activity for each tab press, I used shared element transitions to make it appear that the bottom bar never changed. However this is causing the UI to freeze when switching quickly between tabs. 

When I remove the transitions, it works fine, but the fade in/out is too noticeable. Happy to give more details if needed...

**Comment by aurelhubert** [comment] 2016-04-07 18:04
@mclhrn I think it's a not an expected use case of this library. I've developed it for being used inside a single activity (so I'm not surprised if you tell me that it's laggy if you implement thhis behavior :) ). Can't you use it with fragments or custom views?

**Comment by JadenGu** [comment] 2016-06-07 08:04
Hi, I also met this problem. Sometimes when I switch the tab or scroll the content. it's laggy for a while. even touch the tab. the ripple effect is laggy. 

It doesn't occur every time but a little bit often. My phone is nexus 5 with Android 6.0.1. 

Thanks.

**Comment by aurelhubert** [comment] 2016-06-07 08:10
@JadenGu Are you using the activities like @mclhrn? If yes, it's not the expected implementation, you should use the library with fragments rather than activities and shared transitions.

**Comment by JadenGu** [comment] 2016-06-12 02:44
Hi @aurelhubert , No. I'm just using the fragments rather than activities.

**Comment by aurelhubert** [comment] 2016-06-14 09:54
@JadenGu Okay, so if you use the lib like in the demo, you can open a new issue, but please give more details about your implementations. Most of the time, the freezes come from work executed in the UI thread.

For now, I close this issue because it's not the expected behavior of the library.

**Closed by aurelhubert** 2016-06-14 09:54 UTC
Labels: question
