### ISSUE TITLE
No animation when change tab

### ISSUE THREAD

**Issue by duccong** [aurelhubert/ahbottomnavigation#32] opened 2016-04-07 08:13 UTC
I use android 4.1 animation works fine when change tab.  But when I use android 4.4.2 it does'nt works.
I setted up:
```java
AHBottomNavigationItem item1 = new AHBottomNavigationItem("Home", R.drawable.ic_n_home_selected);
AHBottomNavigationItem item2 = new AHBottomNavigationItem("Chi tiết", R.drawable.ic_n_chitiet_selected);
        
bottomNavigation.addItem(item1);
bottomNavigation.addItem(item2);

bottomNavigation.setAccentColor(Color.parseColor("#0000ff"));
bottomNavigation.setInactiveColor(Color.parseColor("#cc747474"));

bottomNavigation.setCurrentItem(0);
```
where is my fault ?
Thank you.

**Comment by aurelhubert** [comment] 2016-04-07 11:23
@duccong I can't reproduce the problem on the emulator. Do you have more details about your implementation (version of the lib, the layout, your device, etc.) & what do you expect exactly to happen? 

Thanks.

**Comment by duccong** [comment] 2016-04-07 15:19
Hi, tks for your rep. Here my code:
My layout: activity_main.xml
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:weightSum="1">

    <FrameLayout
        android:id="@+id/n_framelayout"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1"></FrameLayout>

    <View
        android:layout_width="match_parent"
        android:layout_height="1px"
        android:background="@android:color/darker_gray" />

    <LinearLayout
        android:background="@android:color/white"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="horizontal">

        <com.aurelhubert.ahbottomnavigation.AHBottomNavigation
            android:id="@+id/bottom_navigation"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"/>

    </LinearLayout>

</LinearLayout>`
And here my code: MainActivity . I just code in onCreate() like under.
`protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        AHBottomNavigation bottomNavigation = (AHBottomNavigation) findViewById(R.id.bottom_navigation);

        AHBottomNavigationItem item1 = new AHBottomNavigationItem("Home", R.drawable.ic_n_home_selected);
        AHBottomNavigationItem item2 = new AHBottomNavigationItem("Detail", R.drawable.ic_n_chitiet_selected);
        AHBottomNavigationItem item3 = new AHBottomNavigationItem("Service", R.drawable.ic_n_dichvu_selected);
        AHBottomNavigationItem item4 = new AHBottomNavigationItem("Discover", R.drawable.ic_n_khampha_selected);
        AHBottomNavigationItem item5 = new AHBottomNavigationItem("Notify", R.drawable.ic_n_thongbao_selected);

        bottomNavigation.addItem(item1);
        bottomNavigation.addItem(item2);
        bottomNavigation.addItem(item3);
        bottomNavigation.addItem(item4);
        bottomNavigation.addItem(item5);

        bottomNavigation.setAccentColor(Color.parseColor("#0000ff"));
        bottomNavigation.setInactiveColor(Color.parseColor("#cc747474"));

        bottomNavigation.setCurrentItem(0);

        // Set listener
        bottomNavigation.setOnTabSelectedListener(new AHBottomNavigation.OnTabSelectedListener() {
            @Override
            public void onTabSelected(int position, boolean wasSelected) {
                // 
            }
        });
`
Lib's version: 1.0.4
My trouble is animation. When change tab, icons will move and change color. 
 On android 4.1.2 it works fine, but on 4.4.2 it it doesn't work. Icons didn't move. Icons appears suddenly as timeAnimation=0.

Thank you.

**Comment by aurelhubert** [comment] 2016-04-07 18:01
Are you testing on a real device ? Can you make a video (http://developer.android.com/tools/help/shell.html#screenrecord) to help me understand what the problem could be?

**Comment by duccong** [comment] 2016-04-08 07:40
Here is my problem. 
[https://youtu.be/sVhZcOO221Q](url)
Thank you.

**Comment by aurelhubert** [comment] 2016-04-08 08:43
Thank you. I think the problem is because you execute a fragment transaction when you click on a tab, and this operation is run on the UI thread, which can cause a lost of frames (typically the frames of the animations). For now, I have found that when you put your fragments fragments directly in the XML and get the reference with the fragment manager (fragmentManager.findFragmentById), the result is clean (mainly because all the fragments are loaded, and you only have to show/hide them in a transaction, with setCustomAnimations if you need).

**Comment by duccong** [comment] 2016-04-08 09:22
i tested and  It work fine on android 4.1, 4.4,5.0, 6.0 but 4.2 it not work.
Thank you.

**Comment by aurelhubert** [comment] 2016-04-08 10:13
But in your example, you show 2 different apps. Do you have different behavior with the same app on different Android version? It could be the device too

**Comment by duccong** [comment] 2016-04-10 05:32
sorry for reply late. I tested 1 app for 2 device. The result still have trouble :)

**Comment by aurelhubert** [comment] 2016-06-03 08:30
I will close this issue. Feel free to test the latest demo project on your phone & re-open the issue if you still encounter the problem, thanks.

**Closed by aurelhubert** 2016-06-03 08:30 UTC
Labels: question
